[build-system]
requires = [
    "setuptools",
    "pybind11",
    "cmake",
]
build-backend = "setuptools.build_meta"

[project]
name = "neuropy"
version = "0.1.0"
dependencies = [
    "numpy",
]

#[tool.setuptools.packages.find]
#include = ["neuropy"]